In [2]:
import torch 

In [4]:
print(torch.__version__)

2.6.0+cu124


In [2]:
print("Number of GPU: ", torch.cuda.device_count())
print("GPU Name: ", torch.cuda.get_device_name())

Number of GPU:  1
GPU Name:  NVIDIA GeForce GTX 1650


In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Using device: cuda


### Creating a Tensor

In [6]:
#using empty
a = torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [9]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#usimg rand
torch.rand(2,3)

tensor([[0.4293, 0.2382, 0.7804],
        [0.0051, 0.4097, 0.2821]])

In [16]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
#other ways

# arange
print("using arange->", torch.arange(0,10,2))

# using linspace
print("using linspace->", torch.linspace(0,10,10))

# using eye
print("using eye ->",torch.eye(5))

#using full 
print("using full ->", torch.full((3,3),5))


using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [4]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [5]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
x.shape

torch.Size([2, 3])

In [7]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7456, 0.3292, 0.4663],
        [0.2173, 0.9166, 0.8793]])

### Tensor Data Types

In [11]:
# find dtype
x.dtype

torch.int64

In [12]:
# assign datatype
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

C:\Users\dubey\AppData\Local\Temp\ipykernel_22640\3139507591.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.0,2.0,3.0], dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [13]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

In [16]:
x = torch.rand(2,2)
x

tensor([[0.4306, 0.1653],
        [0.1950, 0.3250]])

In [18]:
x + 2

tensor([[2.4306, 2.1653],
        [2.1950, 2.3250]])

In [19]:
x - 2

tensor([[-1.5694, -1.8347],
        [-1.8050, -1.6750]])

In [20]:
x/3

tensor([[0.1435, 0.0551],
        [0.0650, 0.1083]])

In [21]:
(x* 100)

tensor([[43.0587, 16.5329],
        [19.4954, 32.5007]])

In [22]:
x**2

tensor([[0.1854, 0.0273],
        [0.0380, 0.1056]])

### Element wise operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6782, 0.4606, 0.2545],
        [0.2375, 0.2250, 0.4747]])
tensor([[0.0480, 0.7449, 0.5937],
        [0.4032, 0.9830, 0.8999]])


In [24]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0061, 0.4606, 0.2545],
        [0.2375, 0.2250, 0.4747]])

In [25]:
c = torch.tensor([1, -2, 3, -4])

In [26]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [29]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction Operation

In [33]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 8., 3.],
        [0., 6., 7.]])

In [34]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18., 13.])

In [35]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 7.0000, 5.0000])

In [36]:
# median
torch.median(e)

tensor(6.)

In [37]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
# product
torch.prod(e)

tensor(0.)

In [39]:
# standard deviation
torch.std(e)

tensor(3.0605)

In [40]:
# variance
torch.var(e)

tensor(9.3667)

In [41]:
# argmax
torch.argmax(e)

tensor(1)

In [42]:
# argmin
torch.argmin(e)

tensor(3)

### Matrix Operations

In [43]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 4, 1],
        [1, 1, 7]])
tensor([[1, 8],
        [0, 0],
        [9, 7]])


In [44]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[13, 39],
        [64, 57]])

In [45]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [46]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 1],
        [4, 1],
        [1, 7]])

In [47]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 2., 0.],
        [7., 4., 7.],
        [0., 8., 7.]])

In [48]:
# determinant
torch.det(h)

tensor(-266.)

In [49]:
# inverse
torch.inverse(h)

tensor([[ 0.1053,  0.0526, -0.0526],
        [ 0.1842, -0.1579,  0.1579],
        [-0.2105,  0.1805, -0.0376]])

### Comparison Operations

In [50]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 2, 0],
        [1, 6, 7]])
tensor([[2, 8, 4],
        [8, 1, 6]])


In [51]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### Special Functions

In [52]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 6., 2.],
        [5., 0., 2.]])

In [53]:
# log
torch.log(k)

tensor([[1.7918, 1.7918, 0.6931],
        [1.6094,   -inf, 0.6931]])

In [54]:
# exp
torch.exp(k)

tensor([[403.4288, 403.4288,   7.3891],
        [148.4132,   1.0000,   7.3891]])

In [55]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.4495, 1.4142],
        [2.2361, 0.0000, 1.4142]])

In [56]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9975, 0.8808],
        [0.9933, 0.5000, 0.8808]])

In [57]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.9975, 0.5000],
        [0.2689, 0.0025, 0.5000]])

In [58]:
# relu
torch.relu(k)

tensor([[6., 6., 2.],
        [5., 0., 2.]])

### Inplace Operations

In [59]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6809, 0.7158, 0.6671],
        [0.2607, 0.2567, 0.8000]])
tensor([[0.0193, 0.8230, 0.0095],
        [0.8144, 0.7047, 0.4329]])


In [60]:
m.add_(n)

tensor([[0.7002, 1.5387, 0.6766],
        [1.0751, 0.9614, 1.2328]])

In [61]:
m

tensor([[0.7002, 1.5387, 0.6766],
        [1.0751, 0.9614, 1.2328]])

In [62]:
n

tensor([[0.0193, 0.8230, 0.0095],
        [0.8144, 0.7047, 0.4329]])

In [63]:
torch.relu(m)

tensor([[0.7002, 1.5387, 0.6766],
        [1.0751, 0.9614, 1.2328]])

In [64]:
m.relu_()

tensor([[0.7002, 1.5387, 0.6766],
        [1.0751, 0.9614, 1.2328]])

In [65]:
m

tensor([[0.7002, 1.5387, 0.6766],
        [1.0751, 0.9614, 1.2328]])

### Copying a Tensor

In [66]:
a = torch.rand(2,3)
a

tensor([[0.7906, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [67]:
b = a

In [68]:
b

tensor([[0.7906, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [69]:
a[0][0] = 0

In [70]:
a

tensor([[0.0000, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [71]:
b

tensor([[0.0000, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [72]:
id(a)

1345052789872

In [73]:
b = a.clone()

In [74]:
a

tensor([[0.0000, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [75]:
b

tensor([[0.0000, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [76]:
a[0][0] = 10

In [77]:
a

tensor([[10.0000,  0.2664,  0.7422],
        [ 0.9788,  0.3842,  0.8497]])

In [78]:
b

tensor([[0.0000, 0.2664, 0.7422],
        [0.9788, 0.3842, 0.8497]])

In [79]:
id(a)

1345052789872

In [80]:
id(b)

1345052798384